# Generated by Django 3.0.5 on 2020-04-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_swap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='postcode',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
