# Generated by Django 3.0.5 on 2020-04-13 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
    ]
