# Generated by Django 3.0.5 on 2020-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_app', '0002_auto_20200417_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, default=1, max_length=4),
            preserve_default=False,
        ),
    ]
